(() => {
  "use strict";
  if(!window.CC_APP?.isDevelopment)throw new Error("Hazard editor requires development bootstrap");
  const ATLAS={na01Hazards:"../assets/worlds/north-america/NA01_HAZARD_ATLAS.png",na01Bird:"../assets/worlds/north-america/NA01_HAZARD_VULTURE.png",na02Hazards:"../assets/worlds/north-america/NA02_HAZARD_ATLAS.png",na02Bird:"../assets/worlds/north-america/NA02_HAZARD_EAGLE.png",na03Hazards:"../assets/worlds/north-america/NA03_HAZARD_ATLAS.png",na03Bird:"../assets/worlds/north-america/NA03_HAZARD_PIGEONS.png",sa01Hazards:"../assets/worlds/south-america/SA01_OBJECT_ATLAS.png",sa01Bird:"../assets/worlds/south-america/SA01_HAZARD_MACAWS.png",sa02Hazards:"../assets/worlds/south-america/SA02_OBJECT_ATLAS.png",sa02Bird:"../assets/worlds/south-america/SA02_HAZARD_ANDEAN_FLAMINGO.png",sa03Hazards:"../assets/worlds/south-america/SA03_OBJECT_ATLAS.png",sa03Bird:"../assets/worlds/south-america/SA03_HAZARD_TROPICAL_PARAKEETS.png",eu01Hazards:"../assets/worlds/europe/EU01_OBJECT_ATLAS_CRATE.png",eu01Barrel:"../assets/worlds/europe/EU01_HAZARD_ROLLING_BARREL.png",eu01Bird:"../assets/worlds/europe/EU01_HAZARD_AEGEAN_GULLS.png",eu02Hazards:"../assets/worlds/europe/EU02_OBJECT_ATLAS.png",eu02Bird:"../assets/worlds/europe/EU02_HAZARD_SWALLOWS.png",eu03Hazards:"../assets/worlds/europe/EU03_OBJECT_ATLAS.png",eu03Bird:"../assets/worlds/europe/EU03_HAZARD_BATS.png"};
  const runtime=()=>document.getElementById("sharedRuntime")?.contentWindow;let activeFrame=0,playing=false,timer=0;
  const selected=()=>{const s=window.CC_DESIGN_SELECTION.current;if(s.type!=="hazard")return null;return{s,h:window.CC_DESIGN_DRAFT.getStage(s.stageId).hazards[s.assetIndex]};};
  function syncToRuntime(stageId,index){const stage=window.CC_DESIGN_DRAFT.getStage(stageId),h=stage.hazards[index],w=runtime();if(!w?.GAME_CONFIG)return false;w.GAME_CONFIG.activeWorld=stageId;w.GAME_CONFIG.objectQA.activeIndex[stageId]=index;const d=w.GAME_CONFIG.objectQA.defs[stageId][index];d.scale=h.transform.scale;d.cw=h.collision.w;d.ch=h.collision.h;d.cx=h.collision.x;d.cy=h.collision.y;d.frames=h.atlas.frames;d.fps=h.animation?.fps||w.GAME_CONFIG.objectQA.flying.fps;d.frameCrops=h.animation?.frameCrops;if(d.kind==="ground")d.groundOffset=h.gameplayAnchor.adjustmentY+h.transform.offsetY;else{w.GAME_CONFIG.objectQA.flying.highClearance=window.GAME_CONFIG.objectQA.flying.highClearance-h.transform.offsetY;w.GAME_CONFIG.objectQA.flying.lowClearance=window.GAME_CONFIG.objectQA.flying.lowClearance-h.transform.offsetY;}if(d.rect)d.rect={...h.atlas.sourceRegion};else{d.frameW=h.atlas.sourceRegion.w;d.frameH=h.atlas.sourceRegion.h;}
    // Phase 7 draft frame crops are resolved dynamically without changing collision geometry.
    const base=h.crop,frames=h.animation?.frameCrops||[base];try{Object.defineProperty(d,"crop",{configurable:true,get(){const f=w.GAME_CONFIG.objectQA.flying.frame||0;return frames[Math.min(frames.length-1,f)]||base;},set(v){/* compatibility writes are intentionally ignored while draft preview is attached */}});}catch{d.crop=frames[activeFrame]||base;}return true;}
  function apply(){if(window.CC_APP.mode!=="design")return;const q=selected();if(!q)return;syncToRuntime(q.s.stageId,q.s.assetIndex);const w=runtime();if(w?.GAME_CONFIG){w.GAME_CONFIG.objectQA.x=window.GAME_CONFIG.objectQA.x+q.h.transform.offsetX;w.GAME_CONFIG.objectQA.showBounds=true;if(!playing)w.GAME_CONFIG.objectQA.flying.frame=activeFrame;}}
  function drawAtlas(canvas,h){const src=ATLAS[h.atlas.key];if(!src)return;const img=new Image();img.onload=()=>{const scale=Math.min(260/img.width,180/img.height);canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const c=canvas.getContext("2d");c.drawImage(img,0,0,canvas.width,canvas.height);const r=h.atlas.sourceRegion;c.strokeStyle="#ffdf5d";c.lineWidth=2;c.strokeRect(r.x*scale+.5,r.y*scale+.5,r.w*scale-1,r.h*scale-1);if((h.atlas.frames||1)>1){const fr={x:r.x+activeFrame*r.w,y:r.y,w:r.w,h:r.h};c.strokeStyle="#63e6ff";c.lineWidth=2;c.strokeRect(fr.x*scale+2.5,fr.y*scale+2.5,fr.w*scale-5,fr.h*scale-5);}};img.src=src;}
  function decorate(){const q=selected();if(window.CC_APP.mode!=="design"||!q)return;const {h}=q,panel=document.getElementById("phase7ContextualInspector");if(!panel)return;panel.querySelector(".full-atlas-view")?.remove();const box=document.createElement("section");box.className="inspector-group full-atlas-view";box.innerHTML="<h3>FULL ATLAS VIEW</h3>";const canvas=document.createElement("canvas");canvas.className="atlas-canvas";const caption=document.createElement("p");caption.className="inspector-note";caption.textContent=`${h.atlas.key} • yellow = animation source • cyan = active frame`;box.append(canvas,caption);if((h.atlas.frames||1)>1){const controls=document.createElement("div");controls.className="animation-preview-controls";const prev=document.createElement("button"),label=document.createElement("strong"),next=document.createElement("button"),play=document.createElement("button");prev.textContent="◀";next.textContent="▶";label.textContent=`FRAME ${activeFrame+1} / ${h.atlas.frames}`;play.textContent=playing?"Ⅱ PAUSE":"▶ PLAY";prev.onclick=()=>selectFrame(activeFrame-1);next.onclick=()=>selectFrame(activeFrame+1);play.onclick=()=>{playing=!playing;decorate();};controls.append(prev,label,next,play);box.append(controls);}panel.insertBefore(box,panel.querySelector(".inspector-actions"));drawAtlas(canvas,h);}
  function selectFrame(n){const q=selected();if(!q)return;activeFrame=(n+(q.h.atlas.frames||1))%(q.h.atlas.frames||1);playing=false;const w=runtime();if(w?.GAME_CONFIG)w.GAME_CONFIG.objectQA.flying.frame=activeFrame;document.dispatchEvent(new CustomEvent("cc-hazard-frame",{detail:{frame:activeFrame}}));decorate();}
  function tick(){const q=selected(),w=runtime();if(playing&&q&&(q.h.atlas.frames||1)>1){const f=w?.GAME_CONFIG?.objectQA?.flying?.frame;if(Number.isInteger(f)&&f!==activeFrame){activeFrame=f;document.dispatchEvent(new CustomEvent("cc-hazard-frame",{detail:{frame:activeFrame}}));decorate();}}timer=requestAnimationFrame(tick);}
  function refresh(){const q=selected();if(q&&activeFrame>=(q.h.atlas.frames||1))activeFrame=0;apply();requestAnimationFrame(decorate);}window.CC_DESIGN_SELECTION.onChange(()=>{activeFrame=0;playing=false;refresh();});window.CC_DESIGN_DRAFT.onChange(refresh);window.CC_APP.onModeChange(refresh);document.addEventListener("cc-inspector-rendered",decorate);document.getElementById("sharedRuntime")?.addEventListener("load",refresh);refresh();timer=requestAnimationFrame(tick);window.CC_HAZARD_EDITOR=Object.freeze({refresh,syncToRuntime,selectFrame,get activeFrame(){return activeFrame;},get playing(){return playing;}});
})();