(() => {
  "use strict";
  if(!window.CC_APP?.isDevelopment)throw new Error("Test mode requires development bootstrap");
  function mount(){
    const host=document.querySelector(".phase7-runtime-host");if(!host||document.getElementById("phase7TestControls"))return;
    let collision=false,ground=false,testType="interaction",interaction={stage:null,character:"claude",hazard:0,flight:"high",state:"run"};
    const panel=document.createElement("aside");panel.id="phase7TestControls";panel.className="phase7-test-controls";
    panel.innerHTML=`<header class="test-panel-header"><strong>TEST MODE</strong><span>Controlled QA workspace</span></header><nav class="test-type-switch" aria-label="Test type"><button type="button" data-type="interaction" class="active">INTERACTION</button><button type="button" data-type="game">GAME</button></nav><section class="test-section test-setup"><h3>SETUP</h3><label>Stage<select id="testStage"></select></label><label>Character<select id="testCharacter"><option value="claude">Claude</option><option value="constance">Constance</option></select></label><div data-interaction><label>Hazard<select id="testHazard"></select></label><label id="testFlightWrap" hidden>Flight<select id="testFlight"><option value="high">HIGH — SLIDE</option><option value="low">LOW — JUMP</option></select></label></div></section><div data-interaction><section class="test-section"><h3>PLAYBACK</h3><div class="test-actions test-actions-primary"><button data-action="play">PLAY</button><button data-action="pause">PAUSE</button><button data-action="resetInteraction">RESET</button></div><div class="test-actions"><button data-action="step">STEP FRAME</button><button data-action="slow">SLOW / NORMAL</button></div></section><section class="test-section"><h3>CHARACTER ACTION</h3><label>State<select id="testState"><option>run</option><option>idle</option><option>jump</option><option>slide</option><option>hit</option><option>celebrate</option></select></label><div class="test-actions"><button data-action="jump">JUMP</button><button data-action="slide">SLIDE</button></div><p class="test-help">Character and hazard share one interaction pass. Pause and step to inspect contact or clearance.</p></section></div><div data-game hidden><section class="test-section"><h3>GAME TEST</h3><div class="test-actions test-actions-primary"><button data-action="run">RUN</button><button data-action="runPause">PAUSE</button><button data-action="reset">RESET</button></div><label class="test-check"><input id="testUnlimited" type="checkbox"> Unlimited Lives</label><p class="test-help">Actual stage gameplay. Keyboard: ↑ Jump · ↓ Slide · Space Pause.</p></section></div><section class="test-section"><h3>DIAGNOSTICS</h3><div class="test-actions"><button data-action="collision">COLLISION BOUNDS</button><button data-action="ground">GROUND GUIDE</button></div></section>`;
    host.prepend(panel);
    const stage=panel.querySelector("#testStage"),character=panel.querySelector("#testCharacter"),hazard=panel.querySelector("#testHazard"),flight=panel.querySelector("#testFlight"),flightWrap=panel.querySelector("#testFlightWrap"),state=panel.querySelector("#testState");
    for(const id of window.GAME_SCHEMA.STAGE_IDS)stage.add(new Option(window.GAME_CONFIG.worldProfiles[id].label,id));
    function fillHazards(preferred){const hs=window.CC_DESIGN_DRAFT.getStage(stage.value).hazards;hazard.replaceChildren();hs.forEach((h,i)=>hazard.add(new Option(h.name,String(i))));hazard.value=String(Math.min(Number(preferred??interaction.hazard)||0,Math.max(0,hs.length-1)));syncHazard();}
    function syncHazard(){const i=Number(hazard.value||0),h=window.CC_DESIGN_DRAFT.getStage(stage.value).hazards[i];interaction.hazard=i;window.CC_HAZARD_EDITOR?.syncToRuntime(stage.value,i);window.CC_RUNTIME_API?.setHazardIndex(i);flightWrap.hidden=h?.kind!=="flying";if(h?.kind==="flying")window.CC_RUNTIME_API?.setFlightMode(flight.value);}
    function endInteraction(){window.CC_RUNTIME_API?.pauseHazardPass();window.CC_RUNTIME_API?.resetHazardPass();}
    function endGame(){window.CC_RUNTIME_API?.resetRun();}
    function switchType(next){if(next!==testType){if(next==="game")endInteraction();else endGame();testType=next;}panel.querySelectorAll("[data-type]").forEach(b=>b.classList.toggle("active",b.dataset.type===next));panel.querySelectorAll("[data-interaction]").forEach(e=>e.hidden=next!=="interaction");panel.querySelectorAll("[data-game]").forEach(e=>e.hidden=next!=="game");if(next==="interaction"){stage.value=interaction.stage||stage.value;character.value=interaction.character;state.value=interaction.state;fillHazards(interaction.hazard);window.CC_RUNTIME_API?.setCharacter(character.value);window.CC_RUNTIME_API?.setCharacterState(state.value);}else{window.CC_RUNTIME_API?.setStage(stage.value);window.CC_RUNTIME_API?.setCharacter(character.value);}}
    stage.onchange=()=>{interaction.stage=stage.value;window.CC_RUNTIME_API?.setStage(stage.value);if(testType==="interaction")fillHazards(0);};character.onchange=()=>{interaction.character=character.value;window.CC_RUNTIME_API?.setCharacter(character.value);};hazard.onchange=syncHazard;flight.onchange=()=>{interaction.flight=flight.value;window.CC_RUNTIME_API?.setFlightMode(flight.value);};state.onchange=()=>{interaction.state=state.value;window.CC_RUNTIME_API?.setCharacterState(state.value);};panel.querySelector("#testUnlimited").onchange=e=>{const w=window.CC_RUNTIME_API?.win();if(w?.GAME_CONFIG)w.GAME_CONFIG.spawnDirector.unlimitedLives=e.target.checked;};
    panel.querySelector(".test-type-switch").addEventListener("click",e=>{const type=e.target.dataset.type;if(type)switchType(type);e.target.blur();});
    panel.addEventListener("click",e=>{const a=e.target.dataset.action;if(!a)return;if(a==="play"){endGame();window.CC_HAZARD_EDITOR?.syncToRuntime(stage.value,Number(hazard.value));window.CC_RUNTIME_API?.setCharacterState(state.value);window.CC_RUNTIME_API?.playHazardPass();}else if(a==="pause"){window.CC_RUNTIME_API?.pauseHazardPass();window.CC_RUNTIME_API?.togglePreviewPause();}else if(a==="resetInteraction"){endInteraction();window.CC_RUNTIME_API?.setCharacterState(state.value);}else if(a==="step")window.CC_RUNTIME_API?.stepPreviewFrame();else if(a==="slow")window.CC_RUNTIME_API?.toggleSlowMotion();else if(a==="jump")window.CC_RUNTIME_API?.interactionJump();else if(a==="slide")window.CC_RUNTIME_API?.interactionSlide();else if(a==="run"){endInteraction();window.CC_RUNTIME_API?.startRun();}else if(a==="runPause")window.CC_RUNTIME_API?.pauseRun();else if(a==="reset")endGame();else if(a==="collision"){collision=!collision;window.CC_RUNTIME_API?.setCollisionBounds(collision);e.target.classList.toggle("active",collision);}else if(a==="ground"){ground=!ground;window.CC_RUNTIME_API?.setGroundGuide(ground);e.target.classList.toggle("active",ground);}e.target.blur();});
    function sync(mode){panel.hidden=mode!=="test";if(panel.hidden){window.CC_RUNTIME_API?.setCollisionBounds(false);window.CC_RUNTIME_API?.setGroundGuide(false);collision=ground=false;return;}const s=window.CC_RUNTIME_API?.getState(),w=window.CC_RUNTIME_API?.win(),design=window.CC_DESIGN_SELECTION?.current;if(design?.stageId)interaction.stage=design.stageId;if(design?.type==="hazard"&&Number.isInteger(design.assetIndex))interaction.hazard=design.assetIndex;stage.value=interaction.stage||s?.stage||window.GAME_CONFIG.activeWorld;character.value=interaction.character||s?.character?.toLowerCase()||"claude";flight.value=interaction.flight;if(w?.GAME_CONFIG)panel.querySelector("#testUnlimited").checked=!!w.GAME_CONFIG.spawnDirector.unlimitedLives;window.CC_RUNTIME_API?.setStage(stage.value);fillHazards(interaction.hazard);switchType(testType);}
    window.CC_APP.onModeChange(sync);window.CC_RUNTIME_API?.frame()?.addEventListener("load",()=>sync(window.CC_APP.mode));sync(window.CC_APP.mode);
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();
})();