const ROOT='../../assets-original/current-generated/';
const stages={NA01:{title:'NORTH AMERICA • STAGE 1',base:'NA-assets/',far:'NA01_BG_DISTANT_MESAS.png',mid:'NA01_BG_MID_DESERT.png',ground:'NA01_GROUND_DESERT.png'},NA02:{title:'NORTH AMERICA • STAGE 2',base:'NA-assets/',far:'NA02_BG_DISTANT_MOUNTAINS.png',mid:'NA02_BG_MID_PINES.png',ground:'NA02_GROUND_TRAIL.png'},NA03:{title:'NORTH AMERICA • STAGE 3',base:'NA-assets/',far:'NA03_BG_DISTANT_NYC.png',mid:'NA03_BG_MID_CITY.png',ground:'NA03_GROUND_CITY.png'},SA01:{title:'SOUTH AMERICA • STAGE 1',base:'SA-assets/',far:'SA01_BG_DISTANT_AMAZON.png',mid:'SA01_BG_MID_AMAZON.png',ground:'SA01_GROUND_AMAZON.png'},SA02:{title:'SOUTH AMERICA • STAGE 2',base:'SA-assets/',far:'SA02_BG_DISTANT_ANDES.png',mid:'SA02_BG_MID_ANDES.png',ground:'SA02_GROUND_ANDES.png'},SA03:{title:'SOUTH AMERICA • STAGE 3',base:'SA-assets/',far:'SA03_BG_DISTANT_RIO.png',mid:'SA03_BG_MID_RIO.png',ground:'SA03_GROUND_RIO.png'},EU01:{title:'EUROPE • STAGE 1',base:'EU-assets/',far:'EU01_BG_DISTANT_GREECE.png',mid:'EU01_BG_MID_GREECE.png',ground:'EU01_GROUND_GREECE.png'},EU02:{title:'EUROPE • STAGE 2',base:'EU-assets/',far:'EU02_BG_DISTANT_PARIS.png',mid:'EU02_BG_MID_PARIS.png',ground:'EU02_GROUND_PARIS.png'},EU03:{title:'EUROPE • STAGE 3',base:'EU-assets/',far:'EU03_BG_DISTANT_BARCELONA.png',mid:'EU03_BG_MID_BARCELONA.png',ground:'EU03_GROUND_BARCELONA.png'}};
const W=480,H=270,BASELINE=205,CONTROL=40,FAR_Y=0,MID_Y=45,GROUND_SOURCE_Y=400,CLOUD_Y=10;
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const cache=new Map();
function load(url){if(cache.has(url))return cache.get(url);const p=new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error(url));i.src=url});cache.set(url,p);return p}function url(s,n){return ROOT+s.base+n}function fit(i){return W/i.width}function drawWidthFit(i,y){const sc=fit(i);ctx.drawImage(i,0,y,W,i.height*sc);return{scale:sc,y,bottom:y+i.height*sc}}
const sel=document.getElementById('stage');Object.keys(stages).forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=k;sel.appendChild(o)});sel.value='SA01';
const heart=ROOT+'HUD/UI_LIFE_HEART.png',path=ROOT+'HUD/UI_STAGE_PROGRESS_PATH.png',marker=ROOT+'HUD/UI_STAGE_PROGRESS_CLAUDE_CONSTANCE.png',run=ROOT+'characer-states/G1A_RUN_CYCLE_ATLAS.png',cloud=ROOT+'NA_CLOUD_LAYER.png';document.getElementById('path').src=path;document.getElementById('marker').src=marker;for(let i=0;i<3;i++){const im=new Image();im.src=heart;if(i)im.style.filter='grayscale(1) brightness(.55)';document.getElementById('hearts').appendChild(im)}
let who='claude';function playerFrame(img){const p=document.getElementById('player');p.src=run;p.style.objectFit='none';const fw=img.width/4,fh=img.height/2;const scale=54/fw;p.style.width=(fw*scale)+'px';p.style.height=(fh*scale)+'px';p.style.objectPosition=who==='claude'?'0 0':'0 100%';p.style.objectFit='contain'}
async function render(){const key=sel.value,s=stages[key];ctx.clearRect(0,0,W,H);try{const [far,mid,ground,cl,runner]=await Promise.all([load(url(s,s.far)),load(url(s,s.mid)),load(url(s,s.ground)),load(cloud),load(run)]);const fb=drawWidthFit(far,FAR_Y);const cb=drawWidthFit(cl,CLOUD_Y);const mb=drawWidthFit(mid,MID_Y);const gs=fit(ground),gy=BASELINE-GROUND_SOURCE_Y*gs;ctx.drawImage(ground,0,gy,W,ground.height*gs);const gb={scale:gs,y:gy,bottom:gy+ground.height*gs};document.getElementById('stageTitle').textContent=s.title;playerFrame(runner);document.getElementById('readout').textContent=`${key} ${s.title}\nFIXED UNIVERSAL GEOMETRY — no stage offsets\nViewer ${W}×${H} | control zone ${CONTROL}px starts Y${H-CONTROL} | player baseline Y${BASELINE}\nFAR: Y${FAR_Y}, width-fit scale ${fb.scale.toFixed(4)}, bottom ${fb.bottom.toFixed(1)}\nCLOUD: Y${CLOUD_Y}, width-fit scale ${cb.scale.toFixed(4)}, bottom ${cb.bottom.toFixed(1)}\nMID: Y${MID_Y}, width-fit scale ${mb.scale.toFixed(4)}, bottom ${mb.bottom.toFixed(1)}\nGROUND: source Y${GROUND_SOURCE_Y}→logical Y${BASELINE}, drawY ${gb.y.toFixed(1)}, bottom ${gb.bottom.toFixed(1)}\nGround image ${gb.bottom>=H-CONTROL?'reaches/passes':'FAILS before'} control boundary Y${H-CONTROL}.\nThis viewer deliberately exposes asset nonconformance instead of compensating per stage.`}catch(e){document.getElementById('readout').textContent='Asset load failed: '+e.message}}
sel.onchange=render;document.getElementById('claude').onclick=()=>{who='claude';render()};document.getElementById('constance').onclick=()=>{who='constance';render()};render();