const ROOT='../assets';
export const ASSET_URLS={
 run:`${ROOT}/characters/G1A_RUN_CYCLE_ATLAS.png`,idle:`${ROOT}/characters/G1B_IDLE_ATLAS.png`,jump:`${ROOT}/characters/G1C_JUMP_ATLAS.png`,slide:`${ROOT}/characters/G1D_SLIDE_ATLAS.png`,hit:`${ROOT}/characters/G1E_HIT_ATLAS.png`,celebrate:`${ROOT}/characters/G1F_CELEBRATE_ATLAS.png`,stars:`${ROOT}/characters/FX_STUN_STARS_ATLAS.png`,clouds:`${ROOT}/shared/NA_CLOUD_LAYER.png`,finish:`${ROOT}/shared/NA_STAGE_FINISH_MARKER.png`,
 far:`${ROOT}/worlds/north-america/NA01_BG_DISTANT_MESAS.png`,mid:`${ROOT}/worlds/north-america/NA01_BG_MID_DESERT.png`,ground:`${ROOT}/worlds/north-america/NA01_GROUND_DESERT.png`,na01Hazards:`${ROOT}/worlds/north-america/NA01_HAZARD_ATLAS.png`,na01Bird:`${ROOT}/worlds/north-america/NA01_HAZARD_VULTURE.png`,
 na02Far:`${ROOT}/worlds/north-america/NA02_BG_DISTANT_MOUNTAINS.png`,na02Mid:`${ROOT}/worlds/north-america/NA02_BG_MID_PINES.png`,na02Ground:`${ROOT}/worlds/north-america/NA02_GROUND_TRAIL.png`,na02Hazards:`${ROOT}/worlds/north-america/NA02_HAZARD_ATLAS.png`,na02Bird:`${ROOT}/worlds/north-america/NA02_HAZARD_EAGLE.png`,
 na03Far:`${ROOT}/worlds/north-america/NA03_BG_DISTANT_NYC.png`,na03Mid:`${ROOT}/worlds/north-america/NA03_BG_MID_CITY.png`,na03Ground:`${ROOT}/worlds/north-america/NA03_GROUND_CITY.png`,na03Hazards:`${ROOT}/worlds/north-america/NA03_HAZARD_ATLAS.png`,na03Bird:`${ROOT}/worlds/north-america/NA03_HAZARD_PIGEONS.png`,
 sa01Far:`${ROOT}/worlds/south-america/SA01_BG_DISTANT_AMAZON.png`,sa01Mid:`${ROOT}/worlds/south-america/SA01_BG_MID_AMAZON.png`,sa01Ground:`${ROOT}/worlds/south-america/SA01_GROUND_AMAZON.png`,sa01Hazards:`${ROOT}/worlds/south-america/SA01_OBJECT_ATLAS.png`,sa01Bird:`${ROOT}/worlds/south-america/SA01_HAZARD_MACAWS.png`,
 sa02Far:`${ROOT}/worlds/south-america/SA02_BG_DISTANT_ANDES.png`,sa02Mid:`${ROOT}/worlds/south-america/SA02_BG_MID_ANDES.png`,sa02Ground:`${ROOT}/worlds/south-america/SA02_GROUND_ANDES.png`,sa02Hazards:`${ROOT}/worlds/south-america/SA02_OBJECT_ATLAS.png`,sa02Bird:`${ROOT}/worlds/south-america/SA02_HAZARD_ANDEAN_FLAMINGO.png`,
 sa03Far:`${ROOT}/worlds/south-america/SA03_BG_DISTANT_RIO.png`,sa03Mid:`${ROOT}/worlds/south-america/SA03_BG_MID_RIO.png`,sa03Ground:`${ROOT}/worlds/south-america/SA03_GROUND_RIO.png`,sa03Hazards:`${ROOT}/worlds/south-america/SA03_OBJECT_ATLAS.png`,sa03Bird:`${ROOT}/worlds/south-america/SA03_HAZARD_TROPICAL_PARAKEETS.png`,
 eu01Far:`${ROOT}/worlds/europe/EU01_BG_DISTANT_GREECE.png`,eu01Mid:`${ROOT}/worlds/europe/EU01_BG_MID_GREECE.png`,eu01Ground:`${ROOT}/worlds/europe/EU01_GROUND_GREECE.png`,eu01Hazards:`${ROOT}/worlds/europe/EU01_OBJECT_ATLAS_CRATE.png`,eu01Barrel:`${ROOT}/worlds/europe/EU01_HAZARD_ROLLING_BARREL.png`,eu01Bird:`${ROOT}/worlds/europe/EU01_HAZARD_AEGEAN_GULLS.png`,
 eu02Far:`${ROOT}/worlds/europe/EU02_BG_DISTANT_PARIS.png`,eu02Mid:`${ROOT}/worlds/europe/EU02_BG_MID_PARIS.png`,eu02Ground:`${ROOT}/worlds/europe/EU02_GROUND_PARIS.png`,eu02Hazards:`${ROOT}/worlds/europe/EU02_OBJECT_ATLAS.png`,eu02Bird:`${ROOT}/worlds/europe/EU02_HAZARD_SWALLOWS.png`,
 eu03Far:`${ROOT}/worlds/europe/EU03_BG_DISTANT_BARCELONA.png`,eu03Mid:`${ROOT}/worlds/europe/EU03_BG_MID_BARCELONA.png`,eu03Ground:`${ROOT}/worlds/europe/EU03_GROUND_BARCELONA.png`,eu03Hazards:`${ROOT}/worlds/europe/EU03_OBJECT_ATLAS.png`,eu03Bird:`${ROOT}/worlds/europe/EU03_HAZARD_BATS.png`
};
export async function loadAssets(){const entries=await Promise.all(Object.entries(ASSET_URLS).map(([key,url])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve([key,img]);img.onerror=()=>reject(new Error(`Asset failed: ${key} ${url}`));img.src=url;})));return Object.fromEntries(entries);}
