import{GAMEPLAY_CONFIG as C}from'./config/gameplay.js';
export class PlayerController{
 constructor(character='claude'){this.character=character;this.state='run';this.frame=0;this.elapsed=0;this.y=0;this.vy=0;this.hitT=0;this.slideT=0;this.timedSlide=false;this.paused=false;this.invulnerable=0;this.visible=true;this.last={centerX:C.characterX,visibleWidth:40,visibleHeight:70,visibleTop:0};}
 setCharacter(v){this.character=v;this.setState('run')} setState(s){if(!C.state[s])return;this.state=s;this.frame=0;this.elapsed=0;this.hitT=0;this.timedSlide=false;this.slideT=0;if(s!=='jump'){this.y=0;this.vy=0}}
 enter(s){this.setState(s)} setPaused(v){this.paused=v;this.setState(v?'idle':'run')} run(){if(!this.paused)this.setState('run')}
 jump(){if(this.paused||this.state==='jump')return;this.state='jump';this.frame=0;this.elapsed=0;this.y=0;this.vy=C.jump.launch}
 slide(){if(this.paused)return;if(this.state!=='slide'){this.state='slide';this.frame=0;this.elapsed=0;this.y=0;this.vy=0}this.timedSlide=true;this.slideT=Math.max(.20,C.actions.slideDuration)}
 hit(){this.state='hit';this.frame=0;this.elapsed=0;this.hitT=0;this.invulnerable=C.hitRecovery.invulnerabilityDuration}
 worldScrolls(){return C.state[this.state].scroll}
 update(dt){if(this.paused)return;this.elapsed+=dt;const cfg=C.state[this.state];if(['run','idle','celebrate'].includes(this.state))this.frame=Math.floor(this.elapsed*cfg.fps)%cfg.frames;if(this.state==='slide'){this.frame=Math.min(1,Math.floor(this.elapsed*cfg.fps));if(this.timedSlide&&(this.slideT-=dt)<=0){this.setState('run');return}}if(this.state==='jump'){this.vy+=C.jump.gravity*dt;this.y+=this.vy*dt;this.frame=this.vy<-110?0:this.vy<110?1:2;if(this.y>=0&&this.vy>0){this.y=0;this.setState('run')}}if(this.state==='hit'){this.hitT+=dt;const hd=C.hitRecovery.recoveryDuration;this.frame=this.hitT<hd*.14?0:this.hitT<hd*.75?1:this.hitT<hd?2:0;if(this.hitT>=hd)this.setState('run')}this.invulnerable=Math.max(0,this.invulnerable-dt);this.visible=this.invulnerable<=0||Math.floor(this.elapsed*12)%2===0;}
 draw(ctx,assets,world,stageProfile){const img=assets[this.state];if(!img)return;const row=this.character==='claude'?0:1,scale=C.masterScale[this.character]*C.stateScale[this.character][this.state],cell=C.cell,sx=this.frame*cell,sy=row*cell,dw=cell*scale,dh=cell*scale,ci=C.cropInsets[this.character]?.[this.state]?.[this.frame]||{l:0,r:0,t:0,b:0},srcW=cell-(ci.l||0)-(ci.r||0),srcH=cell-(ci.t||0)-(ci.b||0),footY=world.lastRenderedSurfaceY+C.footOffset[this.character]+(stageProfile?.characterGrounding?.[this.character]||0),dx=C.characterX-dw/2,dy=footY-dh+this.y,drawX=dx+(ci.l||0)*scale,drawY=dy+(ci.t||0)*scale,drawW=srcW*scale,drawH=srcH*scale;this.last={centerX:drawX+drawW/2,visibleWidth:drawW,visibleHeight:drawH,visibleTop:drawY,footY};if(!this.visible)return;ctx.drawImage(img,sx+(ci.l||0),sy+(ci.t||0),srcW,srcH,Math.round(drawX),Math.round(drawY),Math.round(drawW),Math.round(drawH));}
}
