// Generated by scripts/sync-landscape-registry.cjs.
window.CC_STAGE_CATALOG = {
  "schemaVersion": 1,
  "continents": [
    {
      "id": "north-america",
      "label": "North America",
      "stages": [
        "na01",
        "na02",
        "na03"
      ]
    },
    {
      "id": "south-america",
      "label": "South America",
      "stages": [
        "sa01",
        "sa02",
        "sa03"
      ]
    },
    {
      "id": "europe",
      "label": "Europe",
      "stages": [
        "eu01",
        "eu02",
        "eu03"
      ]
    },
    {
      "id": "africa",
      "label": "Africa",
      "stages": [
        "af01",
        "af02",
        "af03"
      ]
    },
    {
      "id": "asia",
      "label": "Asia",
      "stages": [
        "as01",
        "as02",
        "as03"
      ]
    },
    {
      "id": "oceania",
      "label": "Oceania / Australia",
      "stages": [
        "oc01",
        "oc02",
        "oc03"
      ]
    },
    {
      "id": "antarctica",
      "label": "Antarctica",
      "stages": [
        "an01",
        "an02",
        "an03"
      ]
    }
  ],
  "stages": {
    "na01": {
      "id": "na01",
      "label": "North America — Desert",
      "continent": "north-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 101,
      "files": {}
    },
    "na02": {
      "id": "na02",
      "label": "North America — Pines / Mountains / Stream",
      "continent": "north-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 202,
      "files": {}
    },
    "na03": {
      "id": "na03",
      "label": "North America — City / New York",
      "continent": "north-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 303,
      "files": {}
    },
    "sa01": {
      "id": "sa01",
      "label": "South America — Amazon Rainforest",
      "continent": "south-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 401,
      "files": {}
    },
    "sa02": {
      "id": "sa02",
      "label": "South America — Andes Mountains",
      "continent": "south-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 502,
      "files": {}
    },
    "sa03": {
      "id": "sa03",
      "label": "South America — Rio de Janeiro",
      "continent": "south-america",
      "legacy": true,
      "status": "approved",
      "seedOffset": 603,
      "files": {}
    },
    "eu01": {
      "id": "eu01",
      "label": "Europe — Greece / Santorini",
      "continent": "europe",
      "legacy": true,
      "status": "approved",
      "seedOffset": 701,
      "files": {}
    },
    "eu02": {
      "id": "eu02",
      "label": "Europe — France / Paris",
      "continent": "europe",
      "legacy": true,
      "status": "approved",
      "seedOffset": 802,
      "files": {}
    },
    "eu03": {
      "id": "eu03",
      "label": "Europe — Spain / Barcelona",
      "continent": "europe",
      "legacy": true,
      "status": "approved",
      "seedOffset": 903,
      "files": {}
    },
    "af01": {
      "id": "af01",
      "label": "Tanzania — Serengeti savannah",
      "continent": "africa",
      "legacy": false,
      "status": "integrated",
      "seedOffset": 1001,
      "files": {
        "FAR": "assets/worlds/africa/AF01_BG_DISTANT_SERENGETI.png",
        "MID": "assets/worlds/africa/AF01_BG_MID_SERENGETI.png",
        "GROUND": "assets/worlds/africa/AF01_GROUND_SERENGETI.png",
        "OBJECT_ATLAS": "assets/worlds/africa/AF01_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/africa/AF01_HAZARD_ROLLER.png"
      },
      "release": {
        "status": "integrated",
        "assets": {
          "FAR": {
            "path": "assets/worlds/africa/AF01_BG_DISTANT_SERENGETI.png",
            "sha256": "9d5b06c67359d8557f9ed3b11e2093fa950a7d8b6102d27dee0aba1a105d1868"
          },
          "MID": {
            "path": "assets/worlds/africa/AF01_BG_MID_SERENGETI.png",
            "sha256": "fc8a729f20d143516b4fa93629b765f6b2c6e7137ec24e8628f8ccd200b4e811"
          },
          "GROUND": {
            "path": "assets/worlds/africa/AF01_GROUND_SERENGETI.png",
            "sha256": "96986750f424547467efc7f2cd1723899fa93d5cb8253aa5372a24fd3de83527"
          },
          "OBJECT_ATLAS": {
            "path": "assets/worlds/africa/AF01_OBJECT_ATLAS.png",
            "sha256": "562a90ac93a9f79470cbf0c948d1250ce73e761c086e0419869edbf9bf603569"
          },
          "FLYING": {
            "path": "assets/worlds/africa/AF01_HAZARD_ROLLER.png",
            "sha256": "c9da5f35cdbb7b3b4d14c2ba76708af4895288474c365e0079ff33d51c3f959b"
          }
        },
        "checks": {
          "technical": true,
          "composition": true,
          "contacts": true,
          "animation": true,
          "collision": true,
          "finish": true
        },
        "finish": {
          "scale": 0.22,
          "groundOffset": 6.290625,
          "xOffset": 17.325
        },
        "signature": [
          {
            "time": 75.3,
            "hazard": "GROUND1",
            "speedClass": "normal"
          },
          {
            "time": 77.3,
            "hazard": "FLYING",
            "mode": "high",
            "speedClass": "normal"
          },
          {
            "time": 79.3,
            "hazard": "GROUND2",
            "speedClass": "normal"
          },
          {
            "time": 81.4,
            "hazard": "FLYING",
            "mode": "low",
            "speedClass": "fast"
          },
          {
            "time": 83.4,
            "hazard": "GROUND1",
            "speedClass": "normal"
          }
        ],
        "hazards": [
          {
            "name": "Termite mound",
            "kind": "ground",
            "atlasKey": "af01Hazards",
            "rect": {
              "x": 0,
              "y": 0,
              "w": 1086,
              "h": 724
            },
            "sourceAnchor": {
              "x": 543,
              "y": 620
            },
            "groundOffset": 0,
            "scale": 0.18,
            "crop": {
              "l": 313,
              "r": 312,
              "t": 127,
              "b": 100
            },
            "cw": 0.6941431670281996,
            "ch": 0.9496981891348089,
            "cx": -0.0010845986984815619,
            "cy": 0
          },
          {
            "name": "Crested porcupine",
            "kind": "ground",
            "atlasKey": "af01Hazards",
            "rect": {
              "x": 1086,
              "y": 0,
              "w": 1086,
              "h": 724
            },
            "sourceAnchor": {
              "x": 543,
              "y": 620
            },
            "groundOffset": 0,
            "scale": 0.2,
            "crop": {
              "l": 145,
              "r": 144,
              "t": 213,
              "b": 101
            },
            "cw": 0.5959849435382685,
            "ch": 0.6073170731707317,
            "cx": 0.19949811794228356,
            "cy": 0
          },
          {
            "name": "Lilac-breasted roller",
            "kind": "flying",
            "atlasKey": "af01Bird",
            "frameW": 543,
            "frameH": 724,
            "frames": 4,
            "fps": 8,
            "sourceAnchor": {
              "x": 271,
              "y": 362
            },
            "scale": 0.3,
            "crop": {
              "l": 35,
              "r": 84,
              "t": 95,
              "b": 171
            },
            "cw": 0.4834905660377358,
            "ch": 0.1965065502183406,
            "cx": 0.17806603773584906,
            "cy": 0.07860262008733625,
            "flightOffsetY": {
              "high": 22,
              "low": 0
            }
          }
        ],
        "evidence": "docs/phase8-qa/AF01_STAGE_QA.md"
      }
    },
    "af02": {
      "id": "af02",
      "label": "Namibia — Sossusvlei dunes",
      "continent": "africa",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1102,
      "files": {
        "FAR": "assets/worlds/africa/AF02_BG_DISTANT_SOSSUSVLEI.png",
        "MID": "assets/worlds/africa/AF02_BG_MID_SOSSUSVLEI.png",
        "GROUND": "assets/worlds/africa/AF02_GROUND_SOSSUSVLEI.png",
        "OBJECT_ATLAS": "assets/worlds/africa/AF02_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/africa/AF02_HAZARD_SANDGROUSE.png"
      }
    },
    "af03": {
      "id": "af03",
      "label": "Morocco — Marrakesh medina",
      "continent": "africa",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1203,
      "files": {
        "FAR": "assets/worlds/africa/AF03_BG_DISTANT_MARRAKESH.png",
        "MID": "assets/worlds/africa/AF03_BG_MID_MARRAKESH.png",
        "GROUND": "assets/worlds/africa/AF03_GROUND_MARRAKESH.png",
        "OBJECT_ATLAS": "assets/worlds/africa/AF03_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/africa/AF03_HAZARD_FLYING.png"
      }
    },
    "as01": {
      "id": "as01",
      "label": "Japan — Kyoto bamboo foothills",
      "continent": "asia",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1301,
      "files": {
        "FAR": "assets/worlds/asia/AS01_BG_DISTANT_KYOTO.png",
        "MID": "assets/worlds/asia/AS01_BG_MID_KYOTO.png",
        "GROUND": "assets/worlds/asia/AS01_GROUND_KYOTO.png",
        "OBJECT_ATLAS": "assets/worlds/asia/AS01_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/asia/AS01_HAZARD_WHITE_EYE.png"
      }
    },
    "as02": {
      "id": "as02",
      "label": "China — Zhangjiajie stone forest",
      "continent": "asia",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1402,
      "files": {
        "FAR": "assets/worlds/asia/AS02_BG_DISTANT_ZHANGJIAJIE.png",
        "MID": "assets/worlds/asia/AS02_BG_MID_ZHANGJIAJIE.png",
        "GROUND": "assets/worlds/asia/AS02_GROUND_ZHANGJIAJIE.png",
        "OBJECT_ATLAS": "assets/worlds/asia/AS02_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/asia/AS02_HAZARD_BLUE_MAGPIE.png"
      }
    },
    "as03": {
      "id": "as03",
      "label": "Thailand — Bangkok riverfront",
      "continent": "asia",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1503,
      "files": {
        "FAR": "assets/worlds/asia/AS03_BG_DISTANT_BANGKOK.png",
        "MID": "assets/worlds/asia/AS03_BG_MID_BANGKOK.png",
        "GROUND": "assets/worlds/asia/AS03_GROUND_BANGKOK.png",
        "OBJECT_ATLAS": "assets/worlds/asia/AS03_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/asia/AS03_HAZARD_SWIFT.png"
      }
    },
    "oc01": {
      "id": "oc01",
      "label": "Australia — Uluru red desert",
      "continent": "oceania",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1601,
      "files": {
        "FAR": "assets/worlds/oceania/OC01_BG_DISTANT_ULURU.png",
        "MID": "assets/worlds/oceania/OC01_BG_MID_ULURU.png",
        "GROUND": "assets/worlds/oceania/OC01_GROUND_ULURU.png",
        "OBJECT_ATLAS": "assets/worlds/oceania/OC01_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/oceania/OC01_HAZARD_GALAH.png"
      }
    },
    "oc02": {
      "id": "oc02",
      "label": "Australia — Queensland tropical coast",
      "continent": "oceania",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1702,
      "files": {
        "FAR": "assets/worlds/oceania/OC02_BG_DISTANT_QUEENSLAND.png",
        "MID": "assets/worlds/oceania/OC02_BG_MID_QUEENSLAND.png",
        "GROUND": "assets/worlds/oceania/OC02_GROUND_QUEENSLAND.png",
        "OBJECT_ATLAS": "assets/worlds/oceania/OC02_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/oceania/OC02_HAZARD_LORIKEET.png"
      }
    },
    "oc03": {
      "id": "oc03",
      "label": "New Zealand — Fiordland",
      "continent": "oceania",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1803,
      "files": {
        "FAR": "assets/worlds/oceania/OC03_BG_DISTANT_FIORDLAND.png",
        "MID": "assets/worlds/oceania/OC03_BG_MID_FIORDLAND.png",
        "GROUND": "assets/worlds/oceania/OC03_GROUND_FIORDLAND.png",
        "OBJECT_ATLAS": "assets/worlds/oceania/OC03_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/oceania/OC03_HAZARD_KEA.png"
      }
    },
    "an01": {
      "id": "an01",
      "label": "Antarctic Peninsula — icy coast",
      "continent": "antarctica",
      "legacy": false,
      "status": "pending",
      "seedOffset": 1901,
      "files": {
        "FAR": "assets/worlds/antarctica/AN01_BG_DISTANT_PENINSULA.png",
        "MID": "assets/worlds/antarctica/AN01_BG_MID_PENINSULA.png",
        "GROUND": "assets/worlds/antarctica/AN01_GROUND_PENINSULA.png",
        "OBJECT_ATLAS": "assets/worlds/antarctica/AN01_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/antarctica/AN01_HAZARD_ANTARCTIC_TERN.png"
      }
    },
    "an02": {
      "id": "an02",
      "label": "Ross Island — volcanic shore",
      "continent": "antarctica",
      "legacy": false,
      "status": "pending",
      "seedOffset": 2002,
      "files": {
        "FAR": "assets/worlds/antarctica/AN02_BG_DISTANT_ROSS_ISLAND.png",
        "MID": "assets/worlds/antarctica/AN02_BG_MID_ROSS_ISLAND.png",
        "GROUND": "assets/worlds/antarctica/AN02_GROUND_ROSS_ISLAND.png",
        "OBJECT_ATLAS": "assets/worlds/antarctica/AN02_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/antarctica/AN02_HAZARD_POLAR_SKUA.png"
      }
    },
    "an03": {
      "id": "an03",
      "label": "East Antarctica — coastal research outpost",
      "continent": "antarctica",
      "legacy": false,
      "status": "pending",
      "seedOffset": 2103,
      "files": {
        "FAR": "assets/worlds/antarctica/AN03_BG_DISTANT_RESEARCH_OUTPOST.png",
        "MID": "assets/worlds/antarctica/AN03_BG_MID_RESEARCH_OUTPOST.png",
        "GROUND": "assets/worlds/antarctica/AN03_GROUND_RESEARCH_OUTPOST.png",
        "OBJECT_ATLAS": "assets/worlds/antarctica/AN03_OBJECT_ATLAS.png",
        "FLYING": "assets/worlds/antarctica/AN03_HAZARD_SNOW_PETREL.png"
      }
    }
  }
};
