'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..');
const contract=require('../src/js/stage-contract.js');
const read=(root,p)=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
function build(root=ROOT){
  const landscape=read(root,'config/phase8-landscapes.json'),plan=read(root,'config/remaining-continent-proposal.json'),commands=read(root,'config/asset-commands.json'),releases=read(root,'config/stage-releases.json');
  const stages={},continents=[];
  for(const [prefix,c] of Object.entries(commands.continents)){
    const ids=[1,2,3].map(n=>prefix.toLowerCase()+'0'+n),id=({NA:'north-america',SA:'south-america',EU:'europe',AF:'africa',AS:'asia',OC:'oceania',AN:'antarctica'})[prefix];
    continents.push({id,label:c.label||c.name||prefix,stages:ids});
    for(const [index,key] of ids.entries()){
      const proposed=plan.stages.find(s=>s.id.toLowerCase()===key),legacy=!proposed;
      const files=legacy?{}:{...Object.fromEntries(['FAR','MID','GROUND'].map(k=>[k,proposed.landscapes[k].path])),OBJECT_ATLAS:proposed.groundAtlas,FLYING:proposed.hazards.FLYING.path};
      stages[key]={id:key,label:landscape.stages[key]?.label||proposed.label,continent:id,legacy,status:legacy?'approved':(releases.stages[key]?.status||'pending'),seedOffset:(continents.length-1)*300+(index+1)*101,files};
      if(!legacy&&releases.stages[key]){
        stages[key].release=releases.stages[key];contract.validateRelease(stages[key]);
        if(!['integrated','approved'].includes(landscape.stages[key]?.status))throw new Error(`${key}: release without landscape integration`);
        for(const [selector,asset] of Object.entries(stages[key].release.assets)){
          const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,asset.path))).digest('hex');
          if(actual!==asset.sha256)throw new Error(`${key}/${selector}: release hash mismatch`);
        }
      }
      if(proposed&&['integrated','approved'].includes(landscape.stages[key]?.status)&&!releases.stages[key])throw new Error(`${key}: cannot activate landscapes without the complete stage release`);
    }
  }
  for(const key of Object.keys(releases.stages))if(!stages[key]||stages[key].legacy)throw new Error(`Invalid new-stage release ${key}`);
  return {schemaVersion:1,continents,stages};
}
function render(catalog){return '// Generated by scripts/sync-landscape-registry.cjs.\nwindow.CC_STAGE_CATALOG = '+JSON.stringify(catalog,null,2)+';\n';}
module.exports={build,render};
