import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
import {descriptors} from './workbench-next/model.mjs';import {landscapeDescriptors,drawLandscape} from './workbench-next/landscape.mjs';import {ProjectDraft,projectProvenance} from './workbench-next/project.mjs';import {measureArtwork,optimizeHazard} from './workbench-next/calibration-engine.mjs';
const {createCanvas,loadImage}=createRequire(import.meta.url)('@napi-rs/canvas');
const ctx={window:{}};vm.createContext(ctx);for(const f of JSON.parse(fs.readFileSync('workbench-next/source-files.json')))vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
const w=ctx.window,config=w.GAME_CONFIG;w.CC_LANDSCAPE_CONTRACT.apply(config,w.CC_LANDSCAPE_REGISTRY);const items=descriptors(config,w.GAME_SCHEMA),stages=landscapeDescriptors(config,w.CC_LANDSCAPE_REGISTRY,w.CC_LANDSCAPE_CONTRACT),cat=JSON.parse(fs.readFileSync('workbench-next/asset-catalog.json'));const draft=new ProjectDraft(items,stages,cat.dimensions,projectProvenance(cat,items,stages),cat.migrations,config);
if(process.argv.includes('--before')){draft.placement['hazard:as01:0'].scale=.31;draft.placement['hazard:af03:0'].scale=.23;fs.writeFileSync('../an01-before.json',JSON.stringify(draft.export()));console.log('Prior-save fixture captured');process.exit();}
const prior=JSON.parse(fs.readFileSync('../an01-before.json'));const decoded=draft.decode(prior);console.log('Decoded fields',Object.keys(decoded));
for(const [id,p] of Object.entries(prior.placement))assert.deepEqual(decoded.state.placement[id],p);console.log('All previous placement settings preserved; stages:',stages.length);
const images={};for(const [layer,key] of Object.entries({far:'an01Far',mid:'an01Mid',ground:'an01Ground'})){const source=cat.assets[key];assert(source,key);images[layer]=await loadImage(new URL(source,new URL('./workbench-next/',import.meta.url)));}
for(const scroll of [0,1200,3600]){const canvas=createCanvas(960,540);drawLandscape(canvas,{config,contract:w.CC_LANDSCAPE_CONTRACT,stage:'an01',transforms:draft.landscapes.an01,images,scroll});fs.writeFileSync(`../an01-scene-${scroll}.png`,canvas.toBuffer('image/png'));}
