import fs from 'node:fs';import assert from 'node:assert/strict';import {Node} from './global-dom-harness.mjs';import {setupGlobalGame} from '../dist/workbench-next/global-game.mjs';import {GameAudio} from '../dist/workbench-next/game-audio.mjs';
const memory=new Map(),handlers={},rafs=new Map();let rid=0;
globalThis.document={createElement:t=>new Node(t),hidden:false,addEventListener(){}};globalThis.window={addEventListener:(t,fn)=>(handlers[t]??=[]).push(fn)};globalThis.matchMedia=()=>({matches:false});globalThis.requestAnimationFrame=fn=>{rafs.set(++rid,fn);return rid;};globalThis.cancelAnimationFrame=id=>rafs.delete(id);globalThis.fetch=async p=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('dist/workbench-next/'+p))});globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const engine={ctx:{state:'running'},track:null,claim(o){this.owner=o;},settings(){},unlock:async()=>true,warmEffects(){},resumeMusic(){},setPaused(){},stop(){this.track=null;},musicTrack(id,o={}){if(this.track?.id===id&&!o.force)return;this.track={id,...o};}};
const audio=new GameAudio({engine}),panel=new Node(),surface=new Node();panel.append(surface);let run=null,loads=[],cancelled=0;
const ui=await setupGlobalGame({panel,surface,audio,pause(){},cancelDemo(){cancelled++;},getRun:()=>run,launch:async s=>{loads.push(s);run={stage:s.stage,status:'playing',events:[],motion:{state:'run'}};}});ui.open();const original=JSON.stringify(ui.store.state),raw=[...memory];let clock=0;
async function step(n){for(let i=0;i<n;i++){clock+=100;const callbacks=[...rafs.values()];rafs.clear();for(const f of callbacks)f(clock);for(let j=0;j<8;j++)await Promise.resolve();}}
await step(150);assert.equal(loads.length,0);engine.track.ended=true;await step(2);assert.equal(surface.dataset.globalScreen,'demo');assert(loads[0].demo);assert.equal(loads[0].stage,'na01');assert.equal(loads[0].character,'claude');ui.update({...run,status:'complete',lives:3});assert.equal(JSON.stringify(ui.store.state),original);assert.deepEqual([...memory],raw);await step(182);assert.equal(surface.dataset.globalScreen,'start');assert.equal(engine.track.id,'C_AND_C_TITLE');assert(!engine.track.loop);assert.equal(cancelled,1);
engine.track.ended=true;await step(102);assert.equal(loads.length,2);assert.equal(loads[1].character,'constance');let consumed=0;for(const type of ['pointerdown','click'])for(const fn of handlers[type])fn({type,preventDefault(){consumed++;},stopImmediatePropagation(){}});assert.equal(consumed,2);assert.equal(surface.dataset.globalScreen,'start');assert.equal(JSON.stringify(ui.store.state),original);assert.deepEqual([...memory],raw);
ui.close();await step(250);assert.equal(loads.length,2);console.log('Global attract integration: music-end trigger, demo return/restart, stage/character rotation, input click-through suppression and untouched player save/rewards passed.');
