import assert from 'node:assert/strict';import fs from 'node:fs';
import {AttractCycle,AttractPlayback} from '../dist/workbench-next/attract-mode.mjs';
import {GameAudio} from '../dist/workbench-next/game-audio.mjs';
import {makeDraft,items,config,catalog} from './hazard-upgrade/context.mjs';
import {makeSequence,analyzeProfiles} from '../dist/workbench-next/calibration-engine.mjs';
import {PlayRuntime,runtimeSnapshot} from '../dist/workbench-next/play-runtime.mjs';
let ended=false,starts=[],returns=0;const cycle=new AttractCycle({musicReady:()=>ended,begin:async c=>starts.push(c),end:()=>returns++});cycle.open();await cycle.tick(100,{onTitle:true});assert.equal(starts.length,0);ended=true;await cycle.tick(.1,{onTitle:true});assert.equal(starts.length,1);await cycle.tick(17.9,{});assert.equal(returns,0);await cycle.tick(.1,{});assert.equal(returns,1);assert.equal(cycle.mode,'title');
await cycle.tick(9,{onTitle:true});assert.equal(starts.length,1);cycle.input();await cycle.tick(9,{onTitle:true});assert.equal(starts.length,1);await cycle.tick(1,{onTitle:true});assert.equal(starts.length,2);assert.equal(starts[0].character,'claude');assert.equal(starts[1].character,'constance');assert.equal(starts[1].stageIndex,1);assert(cycle.input());assert.equal(returns,2);assert(!cycle.input());cycle.close();await cycle.tick(100,{onTitle:true});assert.equal(starts.length,2);
let finish;const slow=new AttractCycle({musicReady:()=>true,begin:()=>new Promise(r=>finish=r),end:()=>{}});slow.open();const pending=slow.tick(20,{onTitle:true});assert.equal(slow.mode,'loading');assert(slow.input());finish();await pending;assert.equal(slow.mode,'title');
const hidden=new AttractCycle({musicReady:()=>true,begin:async()=>{},end:()=>{}});hidden.open();await hidden.tick(100,{onTitle:true,visible:false});assert.equal(hidden.idle,0);await hidden.tick(100,{onTitle:false});assert.equal(hidden.idle,0);
const engine={owner:null,track:null,claim(o){this.owner=o;},settings(){},setPaused(){},musicTrack(id,o){if(this.track?.id===id&&!o?.force)return;this.track={id,...o};}};const audio=new GameAudio({engine,enabled:true});audio.screen('start');assert.equal(engine.track.loop,false);const title=engine.track;audio.screen('start');assert.equal(engine.track,title,'character/difficulty changes do not restart title');engine.track.ended=true;audio.screen('start');assert.notEqual(engine.track,title);audio.screen('demo');assert.equal(audio.screenName,'demo');
const draft=makeDraft(),state=draft.decode(JSON.parse(fs.readFileSync('authoring/hazard-upgrade/checked-project.json'))).state;Object.assign(draft,{...state,value:state.crops});const before=JSON.stringify(draft.export());
for(const who of ['claude','constance']){const stage='na01',reports=items.filter(i=>i.type==='hazard'&&i.stage===stage).map(item=>({id:item.id,stage,ready:true,reports:analyzeProfiles({config,draft,items,item,profiles:['standard']}).standard}));const sequence=makeSequence({config,draft,items,reports,stage,seed:config.spawnDirector.seed});const run=new PlayRuntime(runtimeSnapshot({config,draft,items,catalog,stage,character:who,sequence}));run.start();const auto=new AttractPlayback(run);for(let i=0;i<1080;i++)auto.advance(1/60);assert.equal(run.time,18);assert.equal(run.hits,0);assert(run.spawned>0);assert(run.events.some(e=>e.type==='action'));}
assert.equal(JSON.stringify(draft.export()),before);console.log('Attract cycle: title completion, 18-second return, interaction, cancellation, hidden/menu suspension, rotation, title restart and both-character real runtime autoplay passed.');
