import assert from 'node:assert/strict';
import fs from 'node:fs';import crypto from 'node:crypto';
import {AudioEngine} from '../dist/workbench-next/audio-engine.mjs';
import {GameAudio} from '../dist/workbench-next/game-audio.mjs';
import {AUDIO_ASSETS} from '../dist/workbench-next/audio-manifest.mjs';
for(const [id,a] of Object.entries(AUDIO_ASSETS)){const path=new URL('../dist/workbench-next/'+a.url,import.meta.url);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),a.hash,id);}
assert.equal(Object.keys(AUDIO_ASSETS).length,36);
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
class Param{constructor(){this.value=0;}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}cancelScheduledValues(){}}
class Context{constructor(){this.currentTime=0;this.destination={};this.sources=[];}async resume(){}async decodeAudioData(){return {duration:90};}createGain(){return {gain:new Param(),connect(){},disconnect(){}};}createBufferSource(){const s={connect(){},disconnect(){},start(at,offset){this.offset=offset;this.started=true;},stop(at){this.stopped=true;this.stopAt=at;},onended:null};this.sources.push(s);return s;}}
let callbacks=[],fetches=0,now=0;const ctx=new Context(),e=new AudioEngine({contextFactory:()=>ctx,fetcher:async()=>{fetches++;return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)};},clock:()=>now,schedule:f=>{callbacks.push(f);return f;},cancel:f=>{callbacks=callbacks.filter(x=>x!==f);}}),owner={};e.claim(owner);
e.musicTrack('C_AND_C_TITLE');assert.equal(fetches,0,'no decoding before user gesture');await e.unlock();await flush();assert.equal(fetches,1);assert(e.track.voice);ctx.currentTime=12;e.setPaused(true);assert.equal(e.track.offset,12);assert.equal(e.track.voice,null);e.setPaused(false);await flush();assert.equal(e.track.voice.offset,12,'resume exact position');
const old=e.track;e.musicTrack('WORLD_MAP');await flush();assert.equal(e.track.id,'WORLD_MAP');assert(!e.cache.has('C_AND_C_TITLE'),'old music cache evicted');assert.notEqual(e.track,old);
const looping=e.track;callbacks.at(-1)();assert.equal(e.track,looping);assert.equal(e.track.voice.offset,0,'runtime repeat starts new voice with fade');
e.visibility(true);assert.equal(e.track.voice,null);e.visibility(false);await flush();assert(e.track.voice);
e.settings({music:false,sound:true});assert.equal(e.track.voice,null);await e.effect('PLAYER_JUMP');assert.equal(e.effects.length,1);e.setPaused(true);assert.equal(e.effects.length,0);await e.effect('PLAYER_JUMP');assert.equal(e.effects.length,0);await e.effect('UI_BUTTON_CONFIRM');assert.equal(e.effects.length,1,'menus work while gameplay paused');
e.setPaused(false);for(let i=0;i<8;i++)await e.effect('BOSS_WEAPON_FIRE_HIGH');assert.equal(e.effects.filter(v=>v.group==='weapon').length,3);for(let i=0;i<5;i++)await e.effect('UI_BUTTON_CONFIRM');assert.equal(e.effects.filter(v=>v.group==='ui').length,1);
e.settings({music:true,sound:false});assert.equal(e.effects.length,0);await e.effect('PLAYER_HIT');assert.equal(e.effects.length,0);
let ends=0;e.musicTrack('STAGE_COMPLETE',{loop:false,stinger:true,onended:()=>ends++});await flush();e.track.voice.source.onended();assert.equal(ends,1);assert(e.track.ended);e.stop();assert.equal(e.track,null);
// A late fetch cannot make a sound after exit/pause or steal a new music screen.
let resolve;const slow=new AudioEngine({contextFactory:()=>new Context(),fetcher:()=>new Promise(r=>resolve=r)});slow.claim({});await slow.unlock();const pending=slow.effect('PLAYER_HIT');await flush();slow.stop();resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});await pending;assert.equal(slow.effects.length,0);
const unavailable=new AudioEngine({contextFactory:()=>new Context(),fetcher:async()=>({ok:false})});await unavailable.unlock();await unavailable.effect('PLAYER_HIT');unavailable.musicTrack('NA01_THEME');await flush();assert(unavailable.lastError);assert.equal(unavailable.track.voice,null);
// Real event-to-audio contract independent of browser device output.
class LogEngine{constructor(){this.calls=[];this.track=null;}claim(o){this.owner=o;}settings(){}unlock(){return Promise.resolve(true);}warmEffects(){}resumeMusic(){}setPaused(p){this.paused=p;}effect(id){this.calls.push(id);}musicTrack(id,o={}){if(this.track?.id===id&&!o.force)return;this.track=id?{id,...o}:null;this.calls.push(id);}stop(){this.track=null;}}
for(const who of ['claude','constance']){
 const engine=new LogEngine(),a=new GameAudio({engine});a.enable(true);a.screen('game');const run={stage:'na01',who,events:[],motion:{state:'run',frame:0},status:'playing'};a.update(run);assert.equal(engine.track.id,'NA01_THEME');run.events.push({type:'action',action:'jump'},{type:'action',action:'slide'},{type:'hit'});run.motion={state:'hit',frame:0};a.update(run);a.update(run);assert.equal(engine.calls.filter(x=>x==='PLAYER_HIT').length,1);run.motion.frame=1;a.update(run);a.update(run);assert.equal(engine.calls.filter(x=>x==='PLAYER_STUNNED').length,1);
 run.status='complete';a.update(run);a.update(run);assert.equal(engine.calls.filter(x=>x==='STAGE_COMPLETE').length,1);a.result({complete:true},{kind:'passport'});assert.equal(engine.calls.filter(x=>x==='STAGE_COMPLETE').length,1);a.result({complete:true},{kind:'world'});assert.equal(engine.track.id,'STAGE_COMPLETE');engine.track.onended();assert.equal(engine.track.id,'GAME_COMPLETE');
 a.screen('map');assert.equal(engine.track.id,'WORLD_MAP');a.screen('game');const boss={...run,kind:'secret',stage:'secret01',status:'playing',events:[],motion:{state:'run',frame:0},captureDuration:1.7,captureTime:0};a.update(boss);boss.events.push({type:'release',lane:'high'},{type:'release',lane:'low'},{type:'pulse'});a.update(boss);assert(engine.calls.includes('BOSS_WEAPON_FIRE_HIGH'));assert(engine.calls.includes('BOSS_WEAPON_FIRE_LOW'));assert.equal(engine.calls.filter(x=>x==='BOSS_HIT').length,1);boss.status='complete';a.update(boss);assert.equal(engine.track,null);boss.captureTime=1.7;a.update(boss);a.update(boss);assert.equal(engine.calls.filter(x=>x==='BOSS_COMPLETE').length,1);a.stop();const n=engine.calls.length;a.update(boss);assert.equal(engine.calls.length,n);
}
console.log('Audio QA passed: 36 unchanged originals; lazy loading, fades/repeat, pause offsets, mute, backgrounding, missing/late loads, overlap caps, both-character event mapping, completion deduplication and capture timing.');

const clockEngine=new AudioEngine({contextFactory:()=>new Context(),fetcher:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)})});clockEngine.claim({});await clockEngine.unlock();clockEngine.musicTrack('C_AND_C_TITLE',{loop:false});await flush();assert(!clockEngine.musicFinished('C_AND_C_TITLE'));clockEngine.ctx.currentTime=89.99;assert(!clockEngine.musicFinished('C_AND_C_TITLE'));clockEngine.ctx.currentTime=90;assert(!clockEngine.track.ended);assert(clockEngine.musicFinished('C_AND_C_TITLE'),'audio clock detects completion before a delayed ended callback');clockEngine.setPaused(true);assert(!clockEngine.musicFinished('C_AND_C_TITLE'));clockEngine.setPaused(false);await flush();assert(clockEngine.musicFinished('C_AND_C_TITLE'));console.log('Title completion: decoded audio clock fallback and pause/resume passed without relying on source.onended.');
